/// <reference types="jquery" />
/// <reference types="tooltipster" />
import "./foundry/global-external.d.mts";
// PF2e global augmentations – generated by "pnpm run extract:pf2e-types"
import "./pf2e/global.d.ts";
import "./socketlib.d.ts";
