import type { Action } from "@actor/actions/index.js";
import * as balance from "./acrobatics/balance.js";
import * as maneuverInFlight from "./acrobatics/maneuver-in-flight.js";
import * as squeeze from "./acrobatics/squeeze.js";
import * as tumbleThrough from "./acrobatics/tumble-through.js";
import { arcaneSlam } from "./ancestry/automaton/arcane-slam.js";
import * as climb from "./athletics/climb.js";
import * as disarm from "./athletics/disarm.js";
import * as forceOpen from "./athletics/force-open.js";
import * as grapple from "./athletics/grapple.js";
import * as highJump from "./athletics/high-jump.js";
import * as longJump from "./athletics/long-jump.js";
import * as reposition from "./athletics/reposition.js";
import * as shove from "./athletics/shove.js";
import * as swim from "./athletics/swim.js";
import * as trip from "./athletics/trip.js";
import { whirlingThrow } from "./athletics/whirling-throw.js";
import * as escape from "./basic/escape.js";
import * as seek from "./basic/seek.js";
import * as senseMotive from "./basic/sense-motive.js";
import { tamper } from "./class/inventor/tamper.js";
import { craft, repair } from "./crafting/index.js";
import * as createADiversion from "./deception/create-a-diversion.js";
import * as feint from "./deception/feint.js";
import * as impersonate from "./deception/impersonate.js";
import * as lie from "./deception/lie.js";
import { bonMot } from "./diplomacy/bon-mot.js";
import * as gatherInformation from "./diplomacy/gather-information.js";
import * as makeAnImpression from "./diplomacy/make-an-impression.js";
import * as request from "./diplomacy/request.js";
import * as avoidNotice from "./exploration/avoid-notice.js";
import * as senseDirection from "./exploration/sense-direction.js";
import * as track from "./exploration/track.js";
import * as decipherWriting from "./general/decipher-writing.js";
import * as subsist from "./general/subsist.js";
import * as coerce from "./intimidation/coerce.js";
import * as demoralize from "./intimidation/demoralize.js";
import * as administerFirstAid from "./medicine/administer-first-aid.js";
import * as treatDisease from "./medicine/treat-disease.js";
import * as treatPoison from "./medicine/treat-poison.js";
import * as commandAnAnimal from "./nature/command-an-animal.js";
import * as perform from "./performance/perform.js";
import * as createForgery from "./society/create-forgery.js";
import * as concealAnObject from "./stealth/conceal-an-object.js";
import * as hide from "./stealth/hide.js";
import * as sneak from "./stealth/sneak.js";
import * as disableDevice from "./thievery/disable-device.js";
import * as palmAnObject from "./thievery/palm-an-object.js";
import * as pickALock from "./thievery/pick-a-lock.js";
import * as steal from "./thievery/steal.js";
export { ActionMacroHelpers } from "./helpers.js";
export type { ActionDefaultOptions, SkillActionOptions } from "./types.js";
export declare const ActionMacros: {
    escape: typeof escape.legacy;
    seek: typeof seek.legacy;
    senseMotive: typeof senseMotive.legacy;
    arcaneSlam: typeof arcaneSlam;
    tamper: typeof tamper;
    avoidNotice: typeof avoidNotice.legacy;
    senseDirection: typeof senseDirection.legacy;
    track: typeof track.legacy;
    balance: typeof balance.legacy;
    maneuverInFlight: typeof maneuverInFlight.legacy;
    squeeze: typeof squeeze.legacy;
    tumbleThrough: typeof tumbleThrough.legacy;
    climb: typeof climb.legacy;
    disarm: typeof disarm.legacy;
    forceOpen: typeof forceOpen.legacy;
    grapple: typeof grapple.legacy;
    highJump: typeof highJump.legacy;
    longJump: typeof longJump.legacy;
    reposition: typeof reposition.legacy;
    shove: typeof shove.legacy;
    swim: typeof swim.legacy;
    trip: typeof trip.legacy;
    whirlingThrow: typeof whirlingThrow;
    craft: typeof craft;
    repair: typeof repair;
    createADiversion: typeof createADiversion.legacy;
    feint: typeof feint.legacy;
    impersonate: typeof impersonate.legacy;
    lie: typeof lie.legacy;
    bonMot: typeof bonMot;
    gatherInformation: typeof gatherInformation.legacy;
    makeAnImpression: typeof makeAnImpression.legacy;
    request: typeof request.legacy;
    decipherWriting: typeof decipherWriting.legacy;
    subsist: typeof subsist.legacy;
    coerce: typeof coerce.legacy;
    demoralize: typeof demoralize.legacy;
    administerFirstAid: typeof administerFirstAid.legacy;
    treatDisease: typeof treatDisease.legacy;
    treatPoison: typeof treatPoison.legacy;
    commandAnAnimal: typeof commandAnAnimal.legacy;
    perform: typeof perform.legacy;
    createForgery: typeof createForgery.legacy;
    concealAnObject: typeof concealAnObject.legacy;
    hide: typeof hide.legacy;
    sneak: typeof sneak.legacy;
    palmAnObject: typeof palmAnObject.legacy;
    disableDevice: typeof disableDevice.legacy;
    pickALock: typeof pickALock.legacy;
    steal: typeof steal.legacy;
};
declare const SystemActions: Action[];
/**
 * Actions that are only relevant in the starfinder system and sf2e anachronism.
 * @todo Some of these are present in pf2e as well but require more complicated handling.
 */
declare const SF2eOnlySystemActions: (import("@actor/actions/index.ts").SimpleAction | import("@actor/actions/index.ts").SingleCheckAction)[];
export { SF2eOnlySystemActions, SystemActions };
