import type { WeaponGroup, WeaponTrait } from "./types.js";
declare const WEAPON_CATEGORIES: readonly ["unarmed", "simple", "martial", "advanced"];
declare const WEAPON_GROUPS: Set<"poison" | "shield" | "axe" | "bomb" | "bow" | "brawling" | "club" | "corrosive" | "crossbow" | "cryo" | "dart" | "firearm" | "flail" | "flame" | "grenade" | "hammer" | "knife" | "laser" | "mental" | "pick" | "plasma" | "polearm" | "projectile" | "shock" | "sling" | "sniper" | "sonic" | "spear" | "sword">;
declare const MELEE_WEAPON_GROUPS: Set<"shield" | "axe" | "brawling" | "club" | "dart" | "flail" | "hammer" | "knife" | "pick" | "polearm" | "spear" | "sword">;
/** Groups that will be forced as ranged weapons */
declare const MANDATORY_RANGED_GROUPS: Set<WeaponGroup>;
declare const WEAPON_PROPERTY_RUNE_TYPES: Set<"corrosive" | "shock" | "ancestralEchoing" | "anchoring" | "ashen" | "astral" | "authorized" | "bane" | "bloodbane" | "bloodthirsty" | "bolkasBlessing" | "brilliant" | "called" | "coating" | "conducting" | "crushing" | "cunning" | "dancing" | "deathdrinking" | "decaying" | "demolishing" | "disrupting" | "earthbinding" | "energizing" | "extending" | "fanged" | "fearsome" | "flaming" | "flickering" | "flurrying" | "frost" | "ghostTouch" | "giantKilling" | "greaterGiantKilling" | "greaterAnchoring" | "greaterAshen" | "greaterAstral" | "greaterBloodbane" | "greaterBolkasBlessing" | "greaterBrilliant" | "greaterCorrosive" | "greaterCrushing" | "greaterDecaying" | "greaterDisrupting" | "greaterExtending" | "greaterFanged" | "greaterFearsome" | "greaterFlaming" | "greaterFrost" | "greaterHauling" | "greaterImpactful" | "greaterKolssOath" | "greaterRooting" | "greaterShock" | "greaterThundering" | "greaterTruddsStrength" | "grievous" | "hauling" | "holy" | "hopeful" | "hooked" | "impactful" | "impossible" | "keen" | "kinWarding" | "kolssOath" | "majorFanged" | "majorRooting" | "merciful" | "nightmare" | "pacifying" | "returning" | "rooting" | "serrating" | "shifting" | "shockwave" | "speed" | "spellStoring" | "swarming" | "thundering" | "truddsStrength" | "trueRooting" | "underwater" | "unholy" | "vorpal" | "wounding">;
declare const THROWN_RANGES: Set<10 | 100 | 15 | 20 | 30 | 40 | 60 | 80>;
declare const WEAPON_RANGES: Set<10 | 100 | 15 | 20 | 30 | 40 | 60 | 80 | 50 | 70 | 90 | 110 | 120 | 140 | 150 | 180 | 200 | 240 | 300>;
declare const RANGED_ONLY_TRAITS: Set<WeaponTrait>;
declare const MELEE_ONLY_TRAITS: Set<WeaponTrait>;
export { MANDATORY_RANGED_GROUPS, MELEE_ONLY_TRAITS, MELEE_WEAPON_GROUPS, RANGED_ONLY_TRAITS, THROWN_RANGES, WEAPON_CATEGORIES, WEAPON_GROUPS, WEAPON_PROPERTY_RUNE_TYPES, WEAPON_RANGES, };
