import { ActorPF2e, type PartyPF2e } from "@actor";
import type { HitPointsSummary } from "@actor/base.js";
import type { CreatureSource } from "@actor/data/index.js";
import { Modifier } from "@actor/modifiers.js";
import { ActorSpellcasting } from "@actor/spellcasting.js";
import type { SaveType, SkillSlug } from "@actor/types.js";
import type { Rolled } from "@client/dice/_module.d.mts";
import type { DatabaseDeleteCallbackOptions, DatabaseDeleteOperation, DatabaseUpdateOperation } from "@common/abstract/_types.d.mts";
import { ArmorPF2e, ItemPF2e, PhysicalItemPF2e, ShieldPF2e } from "@item";
import type { ItemCarryType } from "@item/physical/data.js";
import type { ItemType } from "@item/types.js";
import type { ActiveEffectPF2e } from "@module/active-effect.js";
import { Rarity, ZeroToTwo } from "@module/data.js";
import type { TokenDocumentPF2e } from "@scene";
import type { CheckRoll } from "@system/check/index.js";
import { Statistic, StatisticDifficultyClass, type ArmorStatistic } from "@system/statistic/index.js";
import { PerceptionStatistic } from "@system/statistic/perception.js";
import { CreatureSystemData, VisionLevel } from "./data.js";
import type { CreatureMovement, CreatureType, CreatureUpdateCallbackOptions, CreatureUpdateOperation, GetReachParameters, ResourceData } from "./types.js";
/** An "actor" in a Pathfinder sense rather than a Foundry one: all should contain attributes and abilities */
declare abstract class CreaturePF2e<TParent extends TokenDocumentPF2e | null = TokenDocumentPF2e | null> extends ActorPF2e<TParent> {
    /** A separate collection of owned spellcasting entries for convenience */
    spellcasting: ActorSpellcasting<this>;
    parties: Set<PartyPF2e>;
    /** A creature always has an AC */
    armorClass: StatisticDifficultyClass<ArmorStatistic>;
    /** Skill checks for the creature, built during data prep */
    skills: Record<string, Statistic<this>>;
    /** Saving throw rolls for the creature, built during data prep */
    saves: Record<SaveType, Statistic>;
    perception: PerceptionStatistic;
    movement: CreatureMovement<this>;
    get allowedItemTypes(): (ItemType | "physical")[];
    /** Types of creatures (as provided by bestiaries 1-3) of which this creature is a member */
    get creatureTypes(): CreatureType[];
    get rarity(): Rarity;
    get hardness(): number;
    /**
     * A currently naive measurement of this creature's reach
     * @param [context.action] The action context of the reach measurement. Interact actions don't consider weapons.
     * @param [context.weapon] The "weapon," literal or otherwise, used in an attack-reach measurement
     */
    getReach({ action, weapon }?: GetReachParameters): number;
    get visionLevel(): VisionLevel;
    get hasDarkvision(): boolean;
    get hasLowLightVision(): boolean;
    get canSee(): boolean;
    get canAct(): boolean;
    get canAttack(): boolean;
    get isDead(): boolean;
    /** Whether the creature emits sound: overridable by AE-like */
    get emitsSound(): boolean;
    get isSpellcaster(): boolean;
    get wornArmor(): ArmorPF2e<this> | null;
    /** Get the held shield of most use to the wielder */
    get heldShield(): ShieldPF2e<this> | null;
    /** Retrieve percpetion and spellcasting statistics */
    getStatistic(slug: SaveType | SkillSlug | "perception"): Statistic<this>;
    getStatistic(slug: string, options?: {
        item: ItemPF2e | null;
    }): Statistic<this> | null;
    protected _initialize(options?: Record<string, unknown>): void;
    prepareData(): void;
    /** Setup base ephemeral data to be modified by active effects and derived-data preparation */
    prepareBaseData(): void;
    prepareEmbeddedDocuments(): void;
    protected prepareDataFromItems(): void;
    prepareDerivedData(): void;
    /** Extract and add custom modifiers. */
    protected prepareSynthetics(): void;
    /**
     * Changes the carry type of an item (held/worn/stowed/etc) and/or regrips/reslots
     * @param item    The item
     * @param options Options to specify how the item should be carried
     */
    changeCarryType(item: PhysicalItemPF2e<CreaturePF2e>, { carryType, handsHeld, inSlot }: ChangeCarryTypeOptions): Promise<void>;
    /**
     * Adds a custom modifier that will be included when determining the final value of a stat. The slug generated by
     * the name parameter must be unique for the custom modifiers for the specified stat, or it will be ignored.
     */
    addCustomModifier(stat: string, label: string, value: number, type: string): Promise<void>;
    /** Removes a custom modifier by slug */
    removeCustomModifier(stat: string, slug: string): Promise<void>;
    /**
     * Roll a Dying Recovery Check
     */
    rollRecovery(event?: PointerEvent): Promise<Rolled<CheckRoll> | null>;
    /** Returns a resource by slug or by key */
    getResource(resource: string): ResourceData | null;
    /**
     * Updates a resource. Redirects to special resources if needed.
     * Accepts resource slugs in both kebab and dromedary, to handle token updates and direct ones.
     */
    updateResource(resource: string, value: number, { render }?: {
        render?: boolean;
    }): Promise<void>;
    /**
     * Prepare this creature's movement data
     * @param modifiers Modifiers in addition to those extracted
     */
    prepareMovementData(modifiers?: Modifier[]): void;
    /** Remove any features linked to a to-be-deleted ABC item */
    deleteEmbeddedDocuments(embeddedName: "ActiveEffect" | "Item", ids: string[], operation?: Partial<DatabaseDeleteOperation<this>>): Promise<ActiveEffectPF2e<this>[] | ItemPF2e<this>[]>;
    protected _preUpdate(changed: DeepPartial<this["_source"]>, options: CreatureUpdateCallbackOptions, user: fd.BaseUser): Promise<boolean | void>;
    /** Overriden to notify the party that an update is required */
    protected _onDelete(options: DatabaseDeleteCallbackOptions, userId: string): void;
}
interface CreaturePF2e<TParent extends TokenDocumentPF2e | null = TokenDocumentPF2e | null> extends ActorPF2e<TParent> {
    readonly _source: CreatureSource;
    system: CreatureSystemData;
    get hitPoints(): HitPointsSummary;
    /** Extend `DatabaseUpdateOperation` for creatures */
    update(data: Record<string, unknown>, operation?: Partial<CreatureUpdateOperation<TParent>>): Promise<this | undefined>;
    /** See implementation in class */
    updateEmbeddedDocuments(embeddedName: "ActiveEffect", updateData: EmbeddedDocumentUpdateData[], operation?: Partial<DatabaseUpdateOperation<this>>): Promise<ActiveEffectPF2e<this>[]>;
    updateEmbeddedDocuments(embeddedName: "Item", updateData: EmbeddedDocumentUpdateData[], operation?: Partial<DatabaseUpdateOperation<this>>): Promise<ItemPF2e<this>[]>;
    updateEmbeddedDocuments(embeddedName: "ActiveEffect" | "Item", updateData: EmbeddedDocumentUpdateData[], operation?: Partial<DatabaseUpdateOperation<this>>): Promise<ActiveEffectPF2e<this>[] | ItemPF2e<this>[]>;
    deleteEmbeddedDocuments(embeddedName: "ActiveEffect", ids: string[], operation?: Partial<DatabaseDeleteOperation<this>>): Promise<ActiveEffectPF2e<this>[]>;
    deleteEmbeddedDocuments(embeddedName: "Item", ids: string[], operation?: Partial<DatabaseDeleteOperation<this>>): Promise<ItemPF2e<this>[]>;
    deleteEmbeddedDocuments(embeddedName: "ActiveEffect" | "Item", ids: string[], operation?: Partial<DatabaseDeleteOperation<this>>): Promise<ActiveEffectPF2e<this>[] | ItemPF2e<this>[]>;
}
interface ChangeCarryTypeOptions {
    /** Whether the item is held, worn, stowed, etc. */
    carryType: ItemCarryType;
    /** If requesting to hold the item, how many holds with which to holt it */
    handsHeld?: ZeroToTwo;
    /** If requesting to wear the item, and the item has a usage slot, whether the item to be in the slot */
    inSlot?: boolean;
}
export { CreaturePF2e };
